export enum RouteNames {
    LOGIN = 'auth::login',
    ONBOARDING = 'onboarding::index',
    DASHBOARD = 'dashboard::index',
    DOMAIN_LIST = 'domains::list',
    DOMAIN_DETAILS = 'domains::details',
    PROJECT_LIST = 'projects::list',
    PROJECT_DETAILS = 'projects::details',
    INBOUND_FORM_DETAILS = 'inboundForms::details',
    INBOUND_FORM_TEMPLATE = 'inboundForms::template',
    BOUNCE_LIST = 'bounces::list',
    SETTINGS = 'settings::index',
    USER_LIST = 'users::list',
    USER_DETAILS = 'users::details',
}
